### ISSUE TITLE
Create the Smart Contract that will hold the anchor file hashes

### ISSUE THREAD

**Issue by ebaizel** [decentralized-identity/sidetree-ethereum#4]
- hold an array of the anchor file hashes (AFH)
- keep a field `nextIndex` that indicates where in the array to write the next AFH
- keep a mapping of bytes32 (the AFH) to uint (the index) to be able to lookup/verify an AFH has been written

Not doing yet:
- limiting who can execute these functions.  We'll want to prevent just anyone from doing that, but that's out of the scope of this ticket.

**Comment by JGuyton501** [comment]
should be done, check dev branch
