### ISSUE TITLE
ERC725 and ERC735

### ISSUE THREAD

**Issue by nathanawmk** [decentralized-identity/sidetree-ethereum#7]
Specifically, how does sidetree-based DID method differ from ERC-725 and ERC-735 implementation? I am working on ERC725 and ERC 735 and am exploring how DID identifiers can be related vis-a-vis Ethereum.

**Comment by ebaizel** [comment]
the initial sidetree work will be for supporting a new DID method and its associated lifecycle CRUD methods.  i believe erc-725 identities will each be anchored in a smart contract, whereas the sidetree DID operations will be batched in a merkle tree with its root hash anchored in a smart contract.

a similar approach using the core sidetree could also be used to store batches of claims; i'm not too familiar with erc-735 but i think those claims would need to live within a smart contract so they can be referenced from other contracts.

@ajunge does this sound correct?

**Comment by OR13** [comment]
Closing this for now.
