### ISSUE TITLE
Persist the batch transaction number in the smart contract

### ISSUE THREAD

**Issue by ebaizel** [decentralized-identity/sidetree-ethereum#9]
https://github.com/decentralized-identity/sidetree-core/blob/master/docs/protocol.md#sidetree-transaction-processing

We'll need to persist the transaction number for each batch.  We'll prob need another mapping to track this, smth like:

```javascript
transactions[transactionNumber - 1] = ipfsHash

// and since we're currently setting the `anchors` mapping(hash) to a boolean, we could set it to the txNumber instead
anchors[ipfsHash] = transactionNumber
```

**Comment by JGuyton501** [comment]
I believe this is done, check the dev branch. Closing.
